//! Deterministic mixed read/write workload — Rust lane.

use polypack_core::{InMemoryStorage, Node, StoreConfig};
use polypack_graph::{Graph, GraphConfig, OrderDirection};
use serde_json::json;
use std::env;
use std::fs;
use std::path::PathBuf;
use std::time::Instant;

const DIMS: usize = 32;
struct Args { initial: usize, rounds: usize, out: PathBuf }
fn args() -> Args { let raw: Vec<String>=env::args().collect(); let mut initial=2000; let mut rounds=200; let mut out=PathBuf::from("benchmarks/results/database-core-mixed-rust.json"); let mut i=1; while i<raw.len(){match raw[i].as_str(){"--initial"=>{initial=raw[i+1].parse().unwrap();i+=2},"--rounds"=>{rounds=raw[i+1].parse().unwrap();i+=2},"--out"=>{out=raw[i+1].clone().into();i+=2},_=>i+=1}} Args{initial,rounds,out} }
struct Rng(u32); impl Rng { fn next(&mut self)->f64 { self.0=self.0.wrapping_add(0x6d2b79f5); let mut t=(self.0^(self.0>>15)).wrapping_mul(self.0|1); t=(t.wrapping_add((t^(t>>7)).wrapping_mul(self.0|61)))^t; ((t^(t>>14)) as f64)/4294967296.0 } }
fn vec(i: usize)->Vec<f64>{let mut r=Rng(i as u32+42);(0..DIMS).map(|_|r.next()*2.0-1.0).collect()}
fn node(i: usize)->Node{Node{id:format!("n{i}"),node_type:if i.is_multiple_of(2){"post".into()}else{"comment".into()},data:{let mut d=serde_json::Map::new();d.insert("score".into(),json!(i));d.insert("bucket".into(),json!(i%10));d.insert("value".into(),json!(i));d},vector:Some(vec(i)),inserted_at:i as i64,updated_at:i as i64,revision:0,activation:None,..Default::default()}}
fn summary(mut v:Vec<f64>)->serde_json::Value{v.sort_by(|a,b|a.partial_cmp(b).unwrap());let at=|p:f64|v[((v.len()as f64*p).ceil()as usize).saturating_sub(1).min(v.len()-1)];json!({"count":v.len(),"p50Ms":at(0.5),"p95Ms":at(0.95),"p99Ms":at(0.99),"opsPerSec":v.len()as f64/(v.iter().sum::<f64>()/1000.0)})}
fn main(){let a=args();let start=Instant::now();let mut g=Graph::open(Box::new(InMemoryStorage::new()),StoreConfig::default(),GraphConfig::default()).unwrap();g.add_nodes((0..a.initial).map(node).collect()).unwrap();g.flush().unwrap();let mut times:Vec<Vec<f64>>=(0..5).map(|_|Vec::with_capacity(a.rounds)).collect();for i in 0..a.rounds{let mut t=Instant::now();g.add_node(node(a.initial+i)).unwrap();g.flush().unwrap();times[0].push(t.elapsed().as_secs_f64()*1000.0);t=Instant::now();let mut d=serde_json::Map::new();d.insert("mixedRound".into(),json!(i));g.update_node(&format!("n{}",i%a.initial),d,None,None).unwrap();g.flush().unwrap();times[1].push(t.elapsed().as_secs_f64()*1000.0);t=Instant::now();let hot=g.query().where_node_type(vec!["post".into()]).where_field("bucket",json!(0)).order_by("score",OrderDirection::Desc).limit(25).ids();times[2].push(t.elapsed().as_secs_f64()*1000.0);if hot.is_empty(){panic!("hot query returned no rows")};t=Instant::now();let persisted=g.query_persisted().where_node_type(vec!["post".into()]).where_field("bucket",json!(0)).order_by("score",OrderDirection::Desc).limit(25).ids().unwrap();times[3].push(t.elapsed().as_secs_f64()*1000.0);if persisted.is_empty(){panic!("persisted query returned no rows")};t=Instant::now();let found=g.similar_to(&vec(i%a.initial),0.0,Some(10)).unwrap();times[4].push(t.elapsed().as_secs_f64()*1000.0);if found.len()!=10{panic!("vector query returned wrong result count")}}
let names=["write","update","hotQuery","persistedQuery","vectorQuery"];let operations=names.iter().zip(times).map(|(n,v)|(n.to_string(),summary(v))).collect::<serde_json::Map<_,_>>();let result=json!({"schemaVersion":1,"lang":"rust","initial":a.initial,"rounds":a.rounds,"dimensions":DIMS,"schedule":"write,update,hotQuery,persistedQuery,vectorQuery","totalMs":start.elapsed().as_secs_f64()*1000.0,"finalNodeCount":g.size(),"operations":operations});if let Some(p)=a.out.parent(){fs::create_dir_all(p).unwrap()}fs::write(&a.out,serde_json::to_string_pretty(&result).unwrap()).unwrap();println!("{}",serde_json::to_string_pretty(&result).unwrap());println!("Wrote {}",a.out.display());}
